## Produces server info
GET http://{{host}}:{{port}}/demo

###
# @name getCustomer
GET http://{{host}}:{{port}}/demo/api/customer/1
Authorization: Bearer {{auth_token}}

###


###
# @name getCustomerWithoutToken
GET http://{{host}}:{{port}}/demo/api/customer/1
Authorization: Bearer {{auth_token}}

###